### ISSUE TITLE
Switch listener from HTTP to HTTPS

### ISSUE THREAD

**Issue by emmanuel** [Nordstrom/kubelogin#15]
Because of the sensitivity of the traffic involved, kubelogin should terminate TLS in the pod.

**Comment by adamcarlton** [comment]
Thought i'd chime in here as well since I want to see the fruits of my labor :P. Looks like what is needed is ListenAndServeTLS which can be found here: `https://golang.org/pkg/net/http/` it'll require a certFile that matches the certs that are being used for the deployment to Kubernetes. I could see this being fine for the server code, however if we made the CLI also use this listener, y'all would have to hand the certFile out to the users.

**Comment by emmanuel** [comment]
@adamcarlton today we did our first fully integrated end-to-end deployment and verification. Your work lives on! Hope your quarter is starting well 💯 .
